// Generated by gencpp from file qingzhou_cloud/qingzhou_cloud.msg
// DO NOT EDIT!


#ifndef QINGZHOU_CLOUD_MESSAGE_QINGZHOU_CLOUD_H
#define QINGZHOU_CLOUD_MESSAGE_QINGZHOU_CLOUD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace qingzhou_cloud
{
template <class ContainerAllocator>
struct qingzhou_cloud_
{
  typedef qingzhou_cloud_<ContainerAllocator> Type;

  qingzhou_cloud_()
    : carstatus(0)  {
    }
  qingzhou_cloud_(const ContainerAllocator& _alloc)
    : carstatus(0)  {
  (void)_alloc;
    }



   typedef uint8_t _carstatus_type;
  _carstatus_type carstatus;





  typedef boost::shared_ptr< ::qingzhou_cloud::qingzhou_cloud_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::qingzhou_cloud::qingzhou_cloud_<ContainerAllocator> const> ConstPtr;

}; // struct qingzhou_cloud_

typedef ::qingzhou_cloud::qingzhou_cloud_<std::allocator<void> > qingzhou_cloud;

typedef boost::shared_ptr< ::qingzhou_cloud::qingzhou_cloud > qingzhou_cloudPtr;
typedef boost::shared_ptr< ::qingzhou_cloud::qingzhou_cloud const> qingzhou_cloudConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::qingzhou_cloud::qingzhou_cloud_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::qingzhou_cloud::qingzhou_cloud_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::qingzhou_cloud::qingzhou_cloud_<ContainerAllocator1> & lhs, const ::qingzhou_cloud::qingzhou_cloud_<ContainerAllocator2> & rhs)
{
  return lhs.carstatus == rhs.carstatus;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::qingzhou_cloud::qingzhou_cloud_<ContainerAllocator1> & lhs, const ::qingzhou_cloud::qingzhou_cloud_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace qingzhou_cloud

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::qingzhou_cloud::qingzhou_cloud_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qingzhou_cloud::qingzhou_cloud_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qingzhou_cloud::qingzhou_cloud_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qingzhou_cloud::qingzhou_cloud_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qingzhou_cloud::qingzhou_cloud_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qingzhou_cloud::qingzhou_cloud_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::qingzhou_cloud::qingzhou_cloud_<ContainerAllocator> >
{
  static const char* value()
  {
    return "86aae73c5c8dd6974b69f6fa57081747";
  }

  static const char* value(const ::qingzhou_cloud::qingzhou_cloud_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x86aae73c5c8dd697ULL;
  static const uint64_t static_value2 = 0x4b69f6fa57081747ULL;
};

template<class ContainerAllocator>
struct DataType< ::qingzhou_cloud::qingzhou_cloud_<ContainerAllocator> >
{
  static const char* value()
  {
    return "qingzhou_cloud/qingzhou_cloud";
  }

  static const char* value(const ::qingzhou_cloud::qingzhou_cloud_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::qingzhou_cloud::qingzhou_cloud_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 carstatus\n"
;
  }

  static const char* value(const ::qingzhou_cloud::qingzhou_cloud_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::qingzhou_cloud::qingzhou_cloud_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.carstatus);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct qingzhou_cloud_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::qingzhou_cloud::qingzhou_cloud_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::qingzhou_cloud::qingzhou_cloud_<ContainerAllocator>& v)
  {
    s << indent << "carstatus: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.carstatus);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QINGZHOU_CLOUD_MESSAGE_QINGZHOU_CLOUD_H
