// Generated by gencpp from file qingzhou_cloud/startstopCommand.msg
// DO NOT EDIT!


#ifndef QINGZHOU_CLOUD_MESSAGE_STARTSTOPCOMMAND_H
#define QINGZHOU_CLOUD_MESSAGE_STARTSTOPCOMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace qingzhou_cloud
{
template <class ContainerAllocator>
struct startstopCommand_
{
  typedef startstopCommand_<ContainerAllocator> Type;

  startstopCommand_()
    : startstopcommand(0)  {
    }
  startstopCommand_(const ContainerAllocator& _alloc)
    : startstopcommand(0)  {
  (void)_alloc;
    }



   typedef uint8_t _startstopcommand_type;
  _startstopcommand_type startstopcommand;





  typedef boost::shared_ptr< ::qingzhou_cloud::startstopCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::qingzhou_cloud::startstopCommand_<ContainerAllocator> const> ConstPtr;

}; // struct startstopCommand_

typedef ::qingzhou_cloud::startstopCommand_<std::allocator<void> > startstopCommand;

typedef boost::shared_ptr< ::qingzhou_cloud::startstopCommand > startstopCommandPtr;
typedef boost::shared_ptr< ::qingzhou_cloud::startstopCommand const> startstopCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::qingzhou_cloud::startstopCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::qingzhou_cloud::startstopCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::qingzhou_cloud::startstopCommand_<ContainerAllocator1> & lhs, const ::qingzhou_cloud::startstopCommand_<ContainerAllocator2> & rhs)
{
  return lhs.startstopcommand == rhs.startstopcommand;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::qingzhou_cloud::startstopCommand_<ContainerAllocator1> & lhs, const ::qingzhou_cloud::startstopCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace qingzhou_cloud

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::qingzhou_cloud::startstopCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qingzhou_cloud::startstopCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qingzhou_cloud::startstopCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qingzhou_cloud::startstopCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qingzhou_cloud::startstopCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qingzhou_cloud::startstopCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::qingzhou_cloud::startstopCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4aaa2a9c02b5667fbf5717c1c2e38c8e";
  }

  static const char* value(const ::qingzhou_cloud::startstopCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4aaa2a9c02b5667fULL;
  static const uint64_t static_value2 = 0xbf5717c1c2e38c8eULL;
};

template<class ContainerAllocator>
struct DataType< ::qingzhou_cloud::startstopCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "qingzhou_cloud/startstopCommand";
  }

  static const char* value(const ::qingzhou_cloud::startstopCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::qingzhou_cloud::startstopCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 startstopcommand\n"
;
  }

  static const char* value(const ::qingzhou_cloud::startstopCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::qingzhou_cloud::startstopCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.startstopcommand);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct startstopCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::qingzhou_cloud::startstopCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::qingzhou_cloud::startstopCommand_<ContainerAllocator>& v)
  {
    s << indent << "startstopcommand: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.startstopcommand);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QINGZHOU_CLOUD_MESSAGE_STARTSTOPCOMMAND_H
