// Generated by gencpp from file qingzhou_cloud/trafficlight.msg
// DO NOT EDIT!


#ifndef QINGZHOU_CLOUD_MESSAGE_TRAFFICLIGHT_H
#define QINGZHOU_CLOUD_MESSAGE_TRAFFICLIGHT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace qingzhou_cloud
{
template <class ContainerAllocator>
struct trafficlight_
{
  typedef trafficlight_<ContainerAllocator> Type;

  trafficlight_()
    : X(0.0)
    , Y(0.0)
    , trafficstatus(0)  {
    }
  trafficlight_(const ContainerAllocator& _alloc)
    : X(0.0)
    , Y(0.0)
    , trafficstatus(0)  {
  (void)_alloc;
    }



   typedef float _X_type;
  _X_type X;

   typedef float _Y_type;
  _Y_type Y;

   typedef int16_t _trafficstatus_type;
  _trafficstatus_type trafficstatus;





  typedef boost::shared_ptr< ::qingzhou_cloud::trafficlight_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::qingzhou_cloud::trafficlight_<ContainerAllocator> const> ConstPtr;

}; // struct trafficlight_

typedef ::qingzhou_cloud::trafficlight_<std::allocator<void> > trafficlight;

typedef boost::shared_ptr< ::qingzhou_cloud::trafficlight > trafficlightPtr;
typedef boost::shared_ptr< ::qingzhou_cloud::trafficlight const> trafficlightConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::qingzhou_cloud::trafficlight_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::qingzhou_cloud::trafficlight_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::qingzhou_cloud::trafficlight_<ContainerAllocator1> & lhs, const ::qingzhou_cloud::trafficlight_<ContainerAllocator2> & rhs)
{
  return lhs.X == rhs.X &&
    lhs.Y == rhs.Y &&
    lhs.trafficstatus == rhs.trafficstatus;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::qingzhou_cloud::trafficlight_<ContainerAllocator1> & lhs, const ::qingzhou_cloud::trafficlight_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace qingzhou_cloud

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::qingzhou_cloud::trafficlight_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qingzhou_cloud::trafficlight_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qingzhou_cloud::trafficlight_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qingzhou_cloud::trafficlight_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qingzhou_cloud::trafficlight_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qingzhou_cloud::trafficlight_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::qingzhou_cloud::trafficlight_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dd7662647ab120aa81de827b8ac271ca";
  }

  static const char* value(const ::qingzhou_cloud::trafficlight_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdd7662647ab120aaULL;
  static const uint64_t static_value2 = 0x81de827b8ac271caULL;
};

template<class ContainerAllocator>
struct DataType< ::qingzhou_cloud::trafficlight_<ContainerAllocator> >
{
  static const char* value()
  {
    return "qingzhou_cloud/trafficlight";
  }

  static const char* value(const ::qingzhou_cloud::trafficlight_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::qingzhou_cloud::trafficlight_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 X\n"
"float32 Y\n"
"int16 trafficstatus\n"
;
  }

  static const char* value(const ::qingzhou_cloud::trafficlight_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::qingzhou_cloud::trafficlight_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.X);
      stream.next(m.Y);
      stream.next(m.trafficstatus);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct trafficlight_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::qingzhou_cloud::trafficlight_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::qingzhou_cloud::trafficlight_<ContainerAllocator>& v)
  {
    s << indent << "X: ";
    Printer<float>::stream(s, indent + "  ", v.X);
    s << indent << "Y: ";
    Printer<float>::stream(s, indent + "  ", v.Y);
    s << indent << "trafficstatus: ";
    Printer<int16_t>::stream(s, indent + "  ", v.trafficstatus);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QINGZHOU_CLOUD_MESSAGE_TRAFFICLIGHT_H
