#map_type: voxel
#map_type: costmap
#robot_radius: 0.25

#footprint: [[0.23,0.19],[0.25,0],[0.23,-0.19],[-0.23, -0.19],[-0.23,0.19]]
# footprint: [[0.23,0.2],[0.23,-0.25],[-0.23, -0.25],[-0.23,0.2]]
footprint: [[0.46,0.2],[0.48,0],[0.46,-0.2],[-0.02, -0.2],[-0.02,0.2]]
recovery_behavior_enabled: true

controller_frequency: 5

always_send_full_costmap: true  #true   局部地图覆盖全局地图

obstacle_layer:
  enabled:              true
  combination_method:   1 #只能设置为0或1，用来更新地图上的代价值，一般设置为1;
  track_unknown_space:  false #如果设置为false，那么地图上代价值就只分为致命碰撞和自由区域两种，如果设置为true，那么就分为致命碰撞，自由区域和未知区域三种。

  origin_z: 0.0
  z_voxels: 20
  z_resolution: 0.1
  unknown_cost_value: 0
  unknown_threshold: 8
  mark_threshold: 0
  publish_voxel_map: false

  obstacle_range: 0.1
  raytrace_range: 0.1
  inflation_radius: 0.25
  #inf_is_valid: true
  max_obstacle_height: 0.40
  min_obstacle_height: 0.03
  controller_frequency: 5 #ypx 4  before 5
  observation_sources: scan 
  #point_cloud_sensor

  scan: {sensor_frame: laser,  observation_persistence: 0.0, 
  max_obstacle_height: 0.3, min_obstacle_height: 0.05, data_type: LaserScan, topic: /scan, 
  marking: true,clearing: true}

inflation_layer:
 enabled:              true
 cost_scaling_factor:  0.01  # exponential rate at which the obstacle cost drops off (default: 10)
 inflation_radius:     0.4  # max. distance from an obstacle at which costs are incurred for planning paths.

static_layer:
 enabled: true
