global_costmap:
  global_frame: map #全局代价地图需要在哪个坐标系下运行;
  robot_base_frame: base_footprint #在全局代价地图中机器人本体的基坐标系，就是机器人上的根坐标系
  # update_frequency: 1.2 #参数决定了代价地图更新的频率（以Hz为单位）。根据传感器数据，全局地图更新的频率，这个数值越大，你的计算机的CPU负担会越重，特别对于全局地图，通常设定一个相对较小、在1.0到5.0之间的值。
  update_frequency: 10.0
  publish_frequency: 10.0
  #static_map: true
  
  rolling_window: false
  resolution: 0.05
  
  transform_tolerance: 1.0  #坐标系间的转换可以忍受的最大延时
  ##map_type: costmap
  ##map_type: voxel
  ##inflation_radius: 0.1
  plugins:
     - {name: static_layer,            type: "costmap_2d::StaticLayer"}
     - {name: obstacle_layer,          type: "costmap_2d::ObstacleLayer"}
     - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}




