#######################################################################
# Copyright: 2016-2018 ROS小课堂 www.corvin.cn
#######################################################################
# Author: corvin
#######################################################################
# Description:
#  该参数文件是为校准小车的角速度而设置，各参数功能介绍分别是：
#  test_angle:测试小车需要转动的角度,默认90度。
#  angle_speed:小车角速度。
#  tolerance_angle:在测试移动时可以容忍的误差。
#  odom_angle_scale:小车在移动中j角速度精度,根据小车实际转动的角度去除以
#    test_angle得到的数据就是，不准确重复运行
#  check_rate:根据小车底盘发布里程计坐标的频率来设置检查的频率.
#  cmd_topic:小车底盘订阅控制其移动的话题名称.
#  base_frame:小车底盘的基坐标系.
#  odom_frame:小车里程计的坐标系,我们需要查询这两个坐标系之间的距离来
#    判断我们的小车是否转动到指定的角度.
#  我们最终标定完以后,只需要记下这个angle_scale参数就可以了.我们需要将
#  该参数配置在控制我们小车底盘移动的上位机代码中.这样我们的小车以后在
#  移动时距离精度就会很好了.
#######################################################################

test_angle: 173  # degrees
angle_speed: 0.3  # rad/s
tolerance_angle: 1.0 # degrees
odom_angle_scale: 1.0
check_rate: 50
cmd_topic: /cmd_vel
base_frame: base_footprint
# base_frame: imu
odom_frame: odom
