// Generated by gencpp from file servicebot/commandServiceRequest.msg
// DO NOT EDIT!


#ifndef SERVICEBOT_MESSAGE_COMMANDSERVICEREQUEST_H
#define SERVICEBOT_MESSAGE_COMMANDSERVICEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace servicebot
{
template <class ContainerAllocator>
struct commandServiceRequest_
{
  typedef commandServiceRequest_<ContainerAllocator> Type;

  commandServiceRequest_()
    : command()
    , args()  {
    }
  commandServiceRequest_(const ContainerAllocator& _alloc)
    : command(_alloc)
    , args(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _command_type;
  _command_type command;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _args_type;
  _args_type args;





  typedef boost::shared_ptr< ::servicebot::commandServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::servicebot::commandServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct commandServiceRequest_

typedef ::servicebot::commandServiceRequest_<std::allocator<void> > commandServiceRequest;

typedef boost::shared_ptr< ::servicebot::commandServiceRequest > commandServiceRequestPtr;
typedef boost::shared_ptr< ::servicebot::commandServiceRequest const> commandServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::servicebot::commandServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::servicebot::commandServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::servicebot::commandServiceRequest_<ContainerAllocator1> & lhs, const ::servicebot::commandServiceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.command == rhs.command &&
    lhs.args == rhs.args;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::servicebot::commandServiceRequest_<ContainerAllocator1> & lhs, const ::servicebot::commandServiceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace servicebot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::servicebot::commandServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::servicebot::commandServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::servicebot::commandServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::servicebot::commandServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::servicebot::commandServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::servicebot::commandServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::servicebot::commandServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3d9a8f5221b63838bd175db24df61819";
  }

  static const char* value(const ::servicebot::commandServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3d9a8f5221b63838ULL;
  static const uint64_t static_value2 = 0xbd175db24df61819ULL;
};

template<class ContainerAllocator>
struct DataType< ::servicebot::commandServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "servicebot/commandServiceRequest";
  }

  static const char* value(const ::servicebot::commandServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::servicebot::commandServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string command\n"
"string args\n"
;
  }

  static const char* value(const ::servicebot::commandServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::servicebot::commandServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
      stream.next(m.args);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct commandServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::servicebot::commandServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::servicebot::commandServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.command);
    s << indent << "args: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.args);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERVICEBOT_MESSAGE_COMMANDSERVICEREQUEST_H
