// Generated by gencpp from file servicebot/commandService.msg
// DO NOT EDIT!


#ifndef SERVICEBOT_MESSAGE_COMMANDSERVICE_H
#define SERVICEBOT_MESSAGE_COMMANDSERVICE_H

#include <ros/service_traits.h>


#include <servicebot/commandServiceRequest.h>
#include <servicebot/commandServiceResponse.h>


namespace servicebot
{

struct commandService
{

typedef commandServiceRequest Request;
typedef commandServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct commandService
} // namespace servicebot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::servicebot::commandService > {
  static const char* value()
  {
    return "9f111e1e5c42601b7c25567189ab6cbd";
  }

  static const char* value(const ::servicebot::commandService&) { return value(); }
};

template<>
struct DataType< ::servicebot::commandService > {
  static const char* value()
  {
    return "servicebot/commandService";
  }

  static const char* value(const ::servicebot::commandService&) { return value(); }
};


// service_traits::MD5Sum< ::servicebot::commandServiceRequest> should match
// service_traits::MD5Sum< ::servicebot::commandService >
template<>
struct MD5Sum< ::servicebot::commandServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::servicebot::commandService >::value();
  }
  static const char* value(const ::servicebot::commandServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::servicebot::commandServiceRequest> should match
// service_traits::DataType< ::servicebot::commandService >
template<>
struct DataType< ::servicebot::commandServiceRequest>
{
  static const char* value()
  {
    return DataType< ::servicebot::commandService >::value();
  }
  static const char* value(const ::servicebot::commandServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::servicebot::commandServiceResponse> should match
// service_traits::MD5Sum< ::servicebot::commandService >
template<>
struct MD5Sum< ::servicebot::commandServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::servicebot::commandService >::value();
  }
  static const char* value(const ::servicebot::commandServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::servicebot::commandServiceResponse> should match
// service_traits::DataType< ::servicebot::commandService >
template<>
struct DataType< ::servicebot::commandServiceResponse>
{
  static const char* value()
  {
    return DataType< ::servicebot::commandService >::value();
  }
  static const char* value(const ::servicebot::commandServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVICEBOT_MESSAGE_COMMANDSERVICE_H
